version: "3"
services:
  api:
    profiles: ["app", "backend", "api"]
    ports:
      - "9999:9999"
    expose:
      - "9999"
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/src
    depends_on:
      - redis_queue
  redis_queue:
    image: redis/redis-stack-server:latest
    profiles: ["app", "redis", "backend"]
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: --save 60 1 --loglevel warning
    volumes:
      # This saves to a local directory
      # - ./data/dev/redis:/data
      # This saves in memory for docker
      - node_redis_volume:/data
  queue_workers:
    profiles: ["app", "workers", "backend"]
    ports:
      - "7777:7777"
    expose:
      - "7777"
    build:
      context: ./workers
      dockerfile: Dockerfile
    volumes:
      - ./workers/src:/app/src
    depends_on:
      - redis_queue
  nginx:
    profiles: ["app", "scraper"]
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8888:80"
    expose:
      - "80"
  browserless_one:
    profiles: ["app", "scraper"]
    image: ghcr.io/browserless/chrome:latest
    environment:
      - HEALTH=true
  browserless_two:
    profiles: ["app", "scraper"]
    image: ghcr.io/browserless/chrome:latest
    environment:
      - HEALTH=true
  web:
    profiles: ["app", "web"]
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./web/src:/app/src
    depends_on:
      - api

volumes:
  node_redis_volume:
